#!/bin/bash

# Skrip untuk menampilkan daftar user SSH dan tanggal kadaluarsanya.

echo "==================================="
echo "  DAFTAR PENGGUNA SSH & OVPN"
echo "==================================="
echo "Username           | Exp. Date"
echo "-----------------------------------"

while read expired; do
    AKUN="$(echo $expired | cut -d: -f1)"
    ID="$(echo $expired | grep -v nobody | cut -d: -f3)"

    if [[ $ID -ge 1000 ]]; then
        exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
        printf "%-18s | %s\n" "$AKUN" "$exp"
    fi
done < /etc/passwd
echo "==================================="
