#!/bin/bash

# Skrip untuk menampilkan daftar user VLESS dari config.json

echo "==================================="
echo "     DAFTAR PENGGUNA VLESS"
echo "==================================="
echo "Username           | Exp. Date"
echo "-----------------------------------"

# Menggunakan grep untuk mencari penanda user VLESS (#&)
grep -E "^#vlg " "/etc/xray/config.json" | cut -d ' ' -f 2,3 | column -t | sort | uniq

if [ $? -ne 0 ] || [ $(grep -c -E "^#vlg " "/etc/xray/config.json") -eq 0 ]; then
    echo "Tidak ada pengguna VLESS yang ditemukan."
fi

echo "==================================="
